#!/bin/bash
#IPAddressList
SYSTEM_PRESET_FILE=/usr/lib/systemd/system-preset/90-default.preset
NTP_UNIT_DIR=/usr/lib/systemd/ntp-units.d
NTP_CONF_FILE=/etc/ntp.conf
DHCP_CONF_DIRECTORY=/etc/dhcp
BACKUP_LOCATION=~esmadmin/backups
OPT=${1}
VALUE=${2}
SEC_VALUE=${3}
THR_VALUE=${4}
PREF_NTP_FROM=${2} #chronyd #Choose ntpd or chronyd
PREF_NTP_TO=${3} #ntpd
PRIMARY_NTP_SERVER=${2}
SECONDARY_NTP_SERVER=${3}


#function USAGE {
#  if [ ${#1} == 0 ] # [${#2} == 0  ]
#    then
#      cat <<-EOF
#usage: $(basename $0) [OPTION] [VALUE]
#                      [Backup_NTP]
#                      [Update_Default_Preset] [NTP NAME FROM] [NTP NAME FROM]
#                      [Update_NTP_UNIT] [NTP NAME FROM] [NTP NAME FROM]
#                      [UpdateNTP_From_Hostname_IP] [PRIMARY NTP SERVER] [SECONDARY NTP SERVER]
#                      [Deactivate_NTP_DHCLIENT] [NTP NAME FROM] [NTP NAME FROM]
#                      [Initiate_NTP]
#EOF
#  elif [ ${#1} != 0 ] && [ ${#2} == 0 ]
#    then
#       ${OPT}
#  else
#    ${OPT} ${2} ${3}
#  fi
#}

function Backup_NTP {
  local Cdate=$(date +%Y%m%d)
  tar cvfP ${BACKUP_LOCATION}/ntp_configuration_backup_${Cdate}.tar ${NTP_UNIT_DIR} ${NTP_CONF_FILE} ${SYSTEM_PRESET_FILE}
}

function Update_Default_Preset {
  if [ -f ${SYSTEM_PRESET_FILE} ]
    then
      sed -i "s/${PREF_NTP_FROM}/${PREF_NTP_TO}/" ${SYSTEM_PRESET_FILE}
  else
    echo "Can not locate the file informaotion"
  fi
}

function Update_NTP_UNIT {
  local RUNLEVEL_PREFIX_FROM=$(ls -1 ${NTP_UNIT_DIR}|grep "${PREF_NTP_FROM}" |sed 's/-.*//')
  local RUNLEVEL_POSTFIX_FROM=$(ls -1 ${NTP_UNIT_DIR}|grep "${PREF_NTP_FROM}" |sed 's/.*-//')
  local RUNLEVEL_PREFIX_TO=$(ls -1 ${NTP_UNIT_DIR}|grep "${PREF_NTP_TO}" |sed 's/-.*//')
  local RUNLEVEL_POSTFIX_TO=$(ls -1 ${NTP_UNIT_DIR}|grep "${PREF_NTP_TO}" |sed 's/.*-//')
  local RUNLEVEL_COMPLETED_TO_FROM=${NTP_UNIT_DIR}/${RUNLEVEL_PREFIX_TO}-${RUNLEVEL_POSTFIX_FROM}
  local RUNLEVEL_COMPLETED_FROM_FROM=${NTP_UNIT_DIR}/${RUNLEVEL_PREFIX_FROM}-${RUNLEVEL_POSTFIX_FROM}
  local RUNLEVEL_COMPLETED_FROM_TO=${NTP_UNIT_DIR}/${RUNLEVEL_PREFIX_FROM}-${RUNLEVEL_POSTFIX_TO}
  local RUNLEVEL_COMPLETED_TO_TO=${NTP_UNIT_DIR}/${RUNLEVEL_PREFIX_TO}-${RUNLEVEL_POSTFIX_TO}
 if [ $((RUNLEVEL_PREFIX_TO)) -gt $((RUNLEVEL_PREFIX_FROM)) ]
    then
        mv ${RUNLEVEL_COMPLETED_FROM_FROM} ${RUNLEVEL_COMPLETED_TO_FROM}
        mv ${RUNLEVEL_COMPLETED_TO_TO} ${RUNLEVEL_COMPLETED_FROM_TO}
    else
      echo "NTP-UNIT list does NOT need any changes"
        fi
}

function UpdateNTP_From_Hostname_IP {
  if [ -f ${NTP_CONF_FILE} ]
    then
    sed -i "/^server*/d" ${NTP_CONF_FILE}
    /bin/cat <<-EOF >> ${NTP_CONF_FILE}
server ${PRIMARY_NTP_SERVER}
server ${SECONDARY_NTP_SERVER}
EOF
  else
    echo "ntp.conf does NOT exist"
 fi
}

function Deactivate_NTP_DHCLIENT.D {
  chmod -x ${DHCP_CONF_DIRECTORY}/dhclient.d/${PREF_NTP_FROM}.sh
  chmod +x ${DHCP_CONF_DIRECTORY}/dhclient.d/${PREF_NTP_TO}.sh
}

function Initiate_NTP {
  timedatectl set-ntp false
  timedatectl set-ntp true
  systemctl restart ntpd
}

case $OPT in
-a)
        if [ ${#2} != 0 ] && [ ${#3} != 0 ] && [ ${#4} == 0 ]
                then
                    A ${2} ${3}
        else
                echo "Invalid Options"
        fi;;
-b)
    B ${2} ;;
-c)
    C ${2} ${3} ${4} ;;
esac

function USAGE {
  if [ ${#OPT} == 0 ] # [${#2} == 0  ]
    then
      cat <<-EOF
usage: $(basename $0) [OPTION] [VALUE]
                      [Backup_NTP]
                      [Update_Default_Preset] [NTP NAME FROM] [NTP NAME FROM]
                      [Update_NTP_UNIT] [NTP NAME FROM] [NTP NAME FROM]
                      [UpdateNTP_From_Hostname_IP] [PRIMARY NTP SERVER] [SECONDARY NTP SERVER]
                      [Deactivate_NTP_DHCLIENT] [NTP NAME FROM] [NTP NAME FROM]
                      [Initiate_NTP]
EOF
#       echo ${#OPT}
  elif [ ${#OPT} != 0 ] && [ ${#VALUE} == 0 ]
    then
        ${OPT}
  else
    ${OPT} ${VAlUE} ${SEC_VALUE}
  fi
}


USAGE

